
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Entry txtProducto1;
	private global::Gtk.Entry txtProducto2;
	private global::Gtk.Entry txtProducto3;
	private global::Gtk.Entry txtSubtotal;
	private global::Gtk.Entry txtIva;
	private global::Gtk.Entry txtTotal;
	private global::Gtk.Label lblTotal;
	private global::Gtk.Label lblSubtotal;
	private global::Gtk.Label lblIva;
	private global::Gtk.Label lblProducto1;
	private global::Gtk.Label lblProducto2;
	private global::Gtk.Label lblProducto3;
	private global::Gtk.Button btnLimpiar;
	private global::Gtk.Button btnFactura;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtProducto1 = new global::Gtk.Entry ();
		this.txtProducto1.CanFocus = true;
		this.txtProducto1.Name = "txtProducto1";
		this.txtProducto1.IsEditable = true;
		this.txtProducto1.InvisibleChar = '●';
		this.fixed1.Add (this.txtProducto1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtProducto1]));
		w1.X = 160;
		w1.Y = 16;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtProducto2 = new global::Gtk.Entry ();
		this.txtProducto2.CanFocus = true;
		this.txtProducto2.Name = "txtProducto2";
		this.txtProducto2.IsEditable = true;
		this.txtProducto2.InvisibleChar = '●';
		this.fixed1.Add (this.txtProducto2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtProducto2]));
		w2.X = 159;
		w2.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtProducto3 = new global::Gtk.Entry ();
		this.txtProducto3.CanFocus = true;
		this.txtProducto3.Name = "txtProducto3";
		this.txtProducto3.IsEditable = true;
		this.txtProducto3.InvisibleChar = '●';
		this.fixed1.Add (this.txtProducto3);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtProducto3]));
		w3.X = 160;
		w3.Y = 84;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtSubtotal = new global::Gtk.Entry ();
		this.txtSubtotal.CanFocus = true;
		this.txtSubtotal.Name = "txtSubtotal";
		this.txtSubtotal.IsEditable = true;
		this.txtSubtotal.InvisibleChar = '●';
		this.fixed1.Add (this.txtSubtotal);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtSubtotal]));
		w4.X = 161;
		w4.Y = 117;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtIva = new global::Gtk.Entry ();
		this.txtIva.CanFocus = true;
		this.txtIva.Name = "txtIva";
		this.txtIva.IsEditable = true;
		this.txtIva.InvisibleChar = '●';
		this.fixed1.Add (this.txtIva);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtIva]));
		w5.X = 160;
		w5.Y = 151;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtTotal = new global::Gtk.Entry ();
		this.txtTotal.CanFocus = true;
		this.txtTotal.Name = "txtTotal";
		this.txtTotal.IsEditable = true;
		this.txtTotal.InvisibleChar = '●';
		this.fixed1.Add (this.txtTotal);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtTotal]));
		w6.X = 159;
		w6.Y = 184;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblTotal = new global::Gtk.Label ();
		this.lblTotal.Name = "lblTotal";
		this.lblTotal.LabelProp = global::Mono.Unix.Catalog.GetString ("Total");
		this.fixed1.Add (this.lblTotal);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblTotal]));
		w7.X = 95;
		w7.Y = 186;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblSubtotal = new global::Gtk.Label ();
		this.lblSubtotal.Name = "lblSubtotal";
		this.lblSubtotal.LabelProp = global::Mono.Unix.Catalog.GetString ("Subtotal");
		this.fixed1.Add (this.lblSubtotal);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblSubtotal]));
		w8.X = 91;
		w8.Y = 120;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblIva = new global::Gtk.Label ();
		this.lblIva.Name = "lblIva";
		this.lblIva.LabelProp = global::Mono.Unix.Catalog.GetString ("IVA");
		this.fixed1.Add (this.lblIva);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblIva]));
		w9.X = 108;
		w9.Y = 154;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblProducto1 = new global::Gtk.Label ();
		this.lblProducto1.Name = "lblProducto1";
		this.lblProducto1.LabelProp = global::Mono.Unix.Catalog.GetString ("Producto 1");
		this.fixed1.Add (this.lblProducto1);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblProducto1]));
		w10.X = 89;
		w10.Y = 21;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblProducto2 = new global::Gtk.Label ();
		this.lblProducto2.Name = "lblProducto2";
		this.lblProducto2.LabelProp = global::Mono.Unix.Catalog.GetString ("Producto 2");
		this.fixed1.Add (this.lblProducto2);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblProducto2]));
		w11.X = 89;
		w11.Y = 51;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblProducto3 = new global::Gtk.Label ();
		this.lblProducto3.Name = "lblProducto3";
		this.lblProducto3.LabelProp = global::Mono.Unix.Catalog.GetString ("Producto 3");
		this.fixed1.Add (this.lblProducto3);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblProducto3]));
		w12.X = 87;
		w12.Y = 83;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnLimpiar = new global::Gtk.Button ();
		this.btnLimpiar.CanFocus = true;
		this.btnLimpiar.Name = "btnLimpiar";
		this.btnLimpiar.UseUnderline = true;
		this.btnLimpiar.Label = global::Mono.Unix.Catalog.GetString ("Limpiar");
		this.fixed1.Add (this.btnLimpiar);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnLimpiar]));
		w13.X = 243;
		w13.Y = 241;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnFactura = new global::Gtk.Button ();
		this.btnFactura.CanFocus = true;
		this.btnFactura.Name = "btnFactura";
		this.btnFactura.UseUnderline = true;
		this.btnFactura.Label = global::Mono.Unix.Catalog.GetString ("Facturar");
		this.fixed1.Add (this.btnFactura);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnFactura]));
		w14.X = 132;
		w14.Y = 240;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 337;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnLimpiar.Clicked += new global::System.EventHandler (this.OnBtnLimpiarClicked);
		this.btnFactura.Clicked += new global::System.EventHandler (this.OnBtnFacturaClicked);
	}
}
